version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  test:
    build: .
    command: python manage.py test
    volumes:
      - .:/code

  filldb:
    build: .
    command: bash -c "python manage.py migrate && python manage.py loaddata fixtures.json"
    volumes:
      - .:/code